// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIQQHriV6WT66D4YFjV77NHt1vyLYmzyQ',
    appId: '1:1039683795018:web:1c802ae3ba803bcf800eb3',
    messagingSenderId: '1039683795018',
    projectId: 'eldercare-23292',
    authDomain: 'eldercare-23292.firebaseapp.com',
    storageBucket: 'eldercare-23292.firebasestorage.app',
    measurementId: 'G-Q3TB88CH3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ43Y3vm41aJWNyJWB4taV28jf1i3kJtI',
    appId: '1:1039683795018:android:3e79489340c6d0b2800eb3',
    messagingSenderId: '1039683795018',
    projectId: 'eldercare-23292',
    storageBucket: 'eldercare-23292.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ-4jRJt54a_y2DLa3y_yGHHLSZm-DV2I',
    appId: '1:1039683795018:ios:d9f292effe3f77ae800eb3',
    messagingSenderId: '1039683795018',
    projectId: 'eldercare-23292',
    storageBucket: 'eldercare-23292.firebasestorage.app',
    iosBundleId: 'com.example.elderlyCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ-4jRJt54a_y2DLa3y_yGHHLSZm-DV2I',
    appId: '1:1039683795018:ios:d9f292effe3f77ae800eb3',
    messagingSenderId: '1039683795018',
    projectId: 'eldercare-23292',
    storageBucket: 'eldercare-23292.firebasestorage.app',
    iosBundleId: 'com.example.elderlyCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIQQHriV6WT66D4YFjV77NHt1vyLYmzyQ',
    appId: '1:1039683795018:web:424eee0f52ab39c2800eb3',
    messagingSenderId: '1039683795018',
    projectId: 'eldercare-23292',
    authDomain: 'eldercare-23292.firebaseapp.com',
    storageBucket: 'eldercare-23292.firebasestorage.app',
    measurementId: 'G-TVNHCN1KBE',
  );
}
